apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sre-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sre-dev.minamiktr.com
    secretName: sre-tls
  rules:
  - host: sre-dev.minamiktr.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sre-app
            port:
              number: 80
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: sre-nginx
            port:
              number: 80
