apiVersion: v1
kind: Service
metadata:
  name: sre-app
  labels:
    app: sre-django
spec:
  ports:
    - port: 8000
  selector:
    app: sre-django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app
  labels:
    app: sre-django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sre-django
  template:
    metadata:
      labels:
        app: sre-django
    spec:
      containers:
      - image: zguanhan/sre-f21-app:latest
        name: django
        env:
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-pass
                key: password
          - name: PG_HOST
            value: sre-postgres
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            value: sreproject
          - name: PG_DATABASE
            value: sreproject
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret-key
                key: secret-key
          - name: EXTERNAL_IP
            value: "*"
        ports:
          - containerPort: 8000
            name: sre-django
