apiVersion: v1
kind: Service
metadata:
  name: sre-app
  labels:
    app: sre-django
spec:
  ports:
    - port: 8000
  selector:
    app: sre-django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app
  labels:
    app: sre-django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sre-django
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sre-django
    spec:
      containers:
      - image: zguanhan/sre-f21-app:latest
        name: django
        env:
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sre-secret
                key: PG_PASSWORD
          - name: PG_HOST
            value: sre-postgres
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: sre-config
                key: PG_USER
          - name: PG_DATABASE
            valueFrom:
              configMapKeyRef:
                name: sre-config
                key: PG_DATABASE
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sre-secret
                key: SECRET_KEY
          - name: EXTERNAL_IP
            value: "*"
        ports:
          - containerPort: 8000
            name: sre-django
