version: "3.7"

services:

  postgres:
    image: "postgres:14.0-alpine3.14"
    logging:
      driver: none
    container_name: postgres-server
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql
    restart: always

  backend:
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:38000:8000"
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - EXTERNAL_IP=${EXTERNAL_IP}
    volumes:
      - type: volume
        source: static-volume
        target: /app/static
    depends_on:
      - postgres
    restart: always

  frontend:
    image: "nginx:1.21.3-alpine"
    ports:
      - "127.0.0.1:10080:80"
    volumes:
      - ./nginx:/etc/nginx/templates
      - type: volume
        source: static-volume
        target: /app/static
    environment:
      - NGINX_HOST=backend
      - STATIC_ROOT=/app
    depends_on:
      - backend
    restart: always


volumes:
  postgres-volume:
  static-volume:
